-- Add missing notification types to the enum
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'TASK_ASSIGNED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'TASK_COMPLETED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'TASK_OVERDUE';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'EVENT_CREATED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'APPROVAL_REQUEST';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'APPROVAL_RESPONSE';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'FAMILY_INVITE';
